// Fetch all reminders
export const GET_REMINDERS = 'GET_REMINDERS';
export const GET_REMINDERS_SUCCESS = 'GET_REMINDERS_SUCCESS';
export const GET_REMINDERS_FAILURE = 'GET_REMINDERS_FAILURE';

// Create a reminder
export const CREATE_REMINDER = 'CREATE_REMINDER';
export const CREATE_REMINDERS_SUCCESS = 'CREATE_REMINDERS_SUCCESS';
export const CREATE_REMINDERS_FAILURE = 'CREATE_REMINDERS_FAILURE';
