# Generated by Django 3.0.3 on 2020-02-23 22:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 22, 14, 45, 52533, tzinfo=utc)),
        ),
    ]
