# Generated by Django 3.0.3 on 2020-03-05 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0005_auto_20200304_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_me_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 23, 22, 25, 667953)),
        ),
    ]
