# Generated by Django 3.0.3 on 2020-03-06 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0008_auto_20200306_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_me_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 11, 22, 35, 5, 38063)),
        ),
    ]
