# Generated by Django 3.0.3 on 2020-03-07 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0009_auto_20200306_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_me_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 12, 15, 38, 44, 422084)),
        ),
    ]
