# Generated by Django 3.0.3 on 2020-03-08 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0010_auto_20200307_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_me_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 18, 54, 48, 81229)),
        ),
    ]
