# Generated by Django 3.0.3 on 2020-03-09 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0011_auto_20200308_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_me_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 14, 20, 24, 42, 502173)),
        ),
    ]
