# Generated by Django 3.0.3 on 2020-03-10 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0012_auto_20200309_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_me_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 17, 45, 25, 528677)),
        ),
    ]
