# Generated by Django 3.0.3 on 2020-03-10 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0013_auto_20200310_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='remind_me_at',
        ),
        migrations.AddField(
            model_name='reminder',
            name='byWho',
            field=models.CharField(default='You', max_length=255),
        ),
        migrations.AddField(
            model_name='reminder',
            name='forWho',
            field=models.CharField(default='You', max_length=255),
        ),
        migrations.AddField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 18, 1, 22, 103304)),
        ),
    ]
