# Generated by Django 3.0.3 on 2020-03-10 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0014_auto_20200310_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 19, 51, 31, 771068)),
        ),
    ]
