# Generated by Django 3.0.3 on 2020-03-10 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0015_auto_20200310_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='extra',
            field=models.CharField(default='Tips...', max_length=255),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 15, 19, 59, 58, 526998)),
        ),
    ]
