# Generated by Django 3.0.3 on 2020-03-11 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0016_auto_20200310_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 16, 20, 11, 41, 625119)),
        ),
    ]
