# Generated by Django 3.0.3 on 2020-03-12 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0018_auto_20200312_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 17, 23, 17, 23, 761340)),
        ),
    ]
