# Generated by Django 3.0.3 on 2020-03-13 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0019_auto_20200312_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 18, 17, 3, 39, 435019)),
        ),
    ]
