# Generated by Django 3.0.3 on 2020-03-15 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0021_auto_20200314_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 20, 17, 38, 36, 782567)),
        ),
    ]
