# Generated by Django 3.0.7 on 2020-06-08 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0023_auto_20200315_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 19, 7, 6, 221995)),
        ),
    ]
