# Generated by Django 3.0.8 on 2020-07-05 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0024_auto_20200608_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 18, 32, 27, 359881)),
        ),
    ]
