# Generated by Django 3.0.8 on 2020-07-05 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0026_auto_20200705_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='remind_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 21, 29, 50, 932564)),
        ),
    ]
