# Generated by Django 3.0.8 on 2020-07-05 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0027_auto_20200705_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='reminder',
            old_name='is_done',
            new_name='isDone',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='remind_at',
        ),
        migrations.AddField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 10, 21, 38, 15, 282297)),
        ),
    ]
