# Generated by Django 3.0.8 on 2020-07-09 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0031_auto_20200709_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 14, 11, 30, 33, 415536)),
        ),
    ]
