# Generated by Django 3.0.8 on 2020-08-02 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0033_auto_20200727_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 8, 10, 19, 602332)),
        ),
    ]
