# Generated by Django 3.0.8 on 2020-08-04 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0035_auto_20200804_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 6, 46, 2, 465683)),
        ),
    ]
