# Generated by Django 3.0.8 on 2020-08-04 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0036_auto_20200804_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 9, 13, 2, 44, 986374)),
        ),
    ]
