# Generated by Django 3.0.8 on 2020-08-05 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0037_auto_20200804_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 10, 6, 58, 49, 249498)),
        ),
    ]
