# Generated by Django 3.0.8 on 2020-08-06 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0038_auto_20200805_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 11, 7, 29, 57, 223987)),
        ),
    ]
