# Generated by Django 3.0.8 on 2020-08-07 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0039_auto_20200806_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 7, 4, 43, 412343)),
        ),
    ]
