# Generated by Django 3.0.8 on 2020-08-07 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0040_auto_20200807_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 12, 17, 24, 27, 351703)),
        ),
    ]
