# Generated by Django 3.0.8 on 2020-08-08 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0041_auto_20200807_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 7, 24, 3, 576732)),
        ),
    ]
