# Generated by Django 3.0.8 on 2020-08-10 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0043_auto_20200809_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 1, 16, 28, 474905)),
        ),
    ]
