# Generated by Django 3.0.8 on 2020-08-10 16:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0044_auto_20200810_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 16, 42, 8, 475530)),
        ),
    ]
