# Generated by Django 3.0.8 on 2020-08-10 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0045_auto_20200810_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 15, 19, 51, 51, 809200)),
        ),
    ]
