# Generated by Django 3.0.8 on 2020-08-13 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0046_auto_20200810_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 17, 16, 29, 496300)),
        ),
    ]
