# Generated by Django 3.0.8 on 2020-08-19 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0047_auto_20200813_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 7, 50, 38, 86787)),
        ),
    ]
