# Generated by Django 3.0.8 on 2020-08-19 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0048_auto_20200819_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 16, 1, 3, 907456)),
        ),
    ]
