# Generated by Django 3.0.8 on 2020-08-19 23:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0049_auto_20200819_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 23, 42, 13, 407090)),
        ),
    ]
