# Generated by Django 3.1.1 on 2020-09-14 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0051_auto_20200913_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 7, 1, 51, 109971)),
        ),
    ]
