# Generated by Django 3.1.1 on 2020-09-15 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0052_auto_20200914_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 6, 4, 10, 503552)),
        ),
    ]
