# Generated by Django 3.1.1 on 2020-09-15 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0053_auto_20200915_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 18, 44, 58, 481079)),
        ),
    ]
