# Generated by Django 3.1.1 on 2020-09-17 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0055_auto_20200916_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 20, 34, 14, 835405)),
        ),
    ]
