# Generated by Django 3.1.1 on 2020-10-03 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0056_auto_20200917_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 11, 33, 30, 369349)),
        ),
    ]
