# Generated by Django 3.1.1 on 2020-10-03 15:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0057_auto_20201003_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 15, 42, 28, 835591)),
        ),
    ]
