# Generated by Django 3.1.1 on 2020-10-09 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0058_auto_20201003_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 14, 16, 28, 4, 606114)),
        ),
    ]
