# Generated by Django 3.1.1 on 2020-10-17 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0059_auto_20201009_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 22, 11, 16, 28, 815053)),
        ),
    ]
