# Generated by Django 3.1.4 on 2020-12-18 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0060_auto_20201017_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 23, 23, 38, 51, 26919)),
        ),
    ]
