# Generated by Django 3.1.4 on 2020-12-19 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0061_auto_20201218_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='remindAt',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 16, 50, 12, 118106)),
        ),
    ]
